/**
 * The board: every shot being watched, where it stands against its deadline, and what
 * the investigator found when it was asked.
 *
 * Deliberately a server component. The board is read on a laptop in a machine room and
 * on a phone in a review theatre, and fetching the shot list from the browser would put
 * the API's URL and its CORS allow-list on a page nobody has a console open in. The one
 * thing that IS a browser call is the Diagnose button, and that is deliberate too: it
 * hits the same public API a judge can hit themselves, so what they watch happening is
 * what is actually happening.
 *
 * Laid out as a clapperboard, per the Slate direction chosen on 2026-08-30 (see the
 * entry's design/DECISION.md). A shot is a card marked SCENE and ROLL; the investigator
 * speaks from a yellow band and yellow is used for nothing else on the page, so a reader
 * can always tell which words were generated by a model.
 *
 * What the layout is organised around is the evidence. A cause on its own is a sentence
 * a model produced, and a supervisor cannot act on it without redoing the investigation.
 * The queries behind it are what make the claim checkable, so they are rendered in full,
 * numbered, in the monospace they would be pasted back into Grafana as, rather than
 * folded behind a disclosure nobody opens at 2am.
 */

import Link from "next/link";

import { describeConfidence, describeSlack, formatEta } from "../delivery";
import { DiagnoseButton } from "../DiagnoseButton";
import { normalizeDiagnosis, type Diagnosis } from "../diagnosis";
import { briefing } from "../briefing";
import { emptyMessage, stalenessNotice } from "../board-state";
import { answeredAgo, provenanceNote } from "../answer-age";
import { apiBase, fetchShots, hasLanded, parseId, percent, type Shot } from "../shots";
import { agreement, agreementNote, normalizeVisual, verdictLabel, type Visual } from "../visual";

// No caching in front of a live delivery board: a cached "ON_TRACK" outliving the shot
// that started failing is the one failure mode this whole project exists to prevent.
export const dynamic = "force-dynamic";

/**
 * The evidence: the queries that were run and what each one showed.
 *
 * Numbered because it is genuinely a sequence - each query followed from the last, and a
 * supervisor talking to a lighting TD says "the second query". Shown in full and allowed
 * to wrap rather than truncated: it is the thing a reader pastes back into Grafana to
 * check the claim, and half of one is no use.
 */
function Evidence({ entries }: { entries: Diagnosis["evidence"] }) {
  if (entries.length === 0) {
    // Reachable: DIAGNOSIS_SCHEMA requires at least one entry, so an answer without any
    // has already broken its contract. Saying so is more use than an absent section that
    // reads as though nobody looked.
    return (
      <ol>
        <li>
          <p>This answer arrived with no queries behind it.</p>
        </li>
      </ol>
    );
  }
  return (
    <ol>
      {entries.map((entry, index) => (
        <li key={index}>
          {entry.query ? (
            <code>{entry.query}</code>
          ) : (
            <code>No query was reported for this finding.</code>
          )}
          {entry.finding ? <p>{entry.finding}</p> : null}
        </li>
      ))}
    </ol>
  );
}

/** Everything the investigator said about one shot. */
function Report({
  shotId,
  diagnosis,
  answeredAt,
  stale,
  nowEpoch,
}: {
  shotId: string;
  diagnosis: Diagnosis;
  answeredAt?: number | null;
  stale?: boolean;
  nowEpoch: number;
}) {
  const { shot } = parseId(shotId);
  const age = answeredAgo(answeredAt, nowEpoch);
  const provenance = provenanceNote(Boolean(stale));
  return (
    <section className="report" aria-label={`Investigator diagnosis for ${shot}`}>
      <div className="rhead">
        <b>Investigator</b>
        <span>
          {shot}
          {diagnosis.confidence ? ` · ${diagnosis.confidence} confidence` : ""}
          {` · ${diagnosis.evidence.length} quer${diagnosis.evidence.length === 1 ? "y" : "ies"}`}
          {age ? ` · answered ${age}` : ""}
          {/* Marked rather than merely appended. This is the one part of the header that
              says the current agent may not stand behind what follows, and it has to
              survive a reader skimming the line. */}
          {provenance ? (
            <>
              {" · "}
              <em className="stale">{provenance}</em>
            </>
          ) : null}
        </span>
      </div>

      {diagnosis.cause ? <p className="cause">{diagnosis.cause}</p> : null}

      {diagnosis.affectedFrames !== null || diagnosis.recommendedAction !== null ? (
        <div className="cols">
          {diagnosis.affectedFrames !== null ? (
            <div>
              <h4>Affected frames</h4>
              <p>{diagnosis.affectedFrames}</p>
            </div>
          ) : null}
          {diagnosis.recommendedAction !== null ? (
            <div>
              <h4>Recommended action</h4>
              <p>{diagnosis.recommendedAction}</p>
            </div>
          ) : null}
        </div>
      ) : null}

      <Evidence entries={diagnosis.evidence} />
    </section>
  );
}

/**
 * What the frame itself looks like, and how that sits against the telemetry.
 *
 * Rendered as its own block rather than folded into the diagnosis, because it is a
 * second source. The relationship line is the reason both exist: a supervisor at 2am
 * will not diff two paragraphs, and a clean-looking frame beside a reported cause is
 * the one result neither check could have produced alone.
 */
function VisualPanel({
  visual,
  telemetryFoundProblem,
}: {
  visual: Visual;
  telemetryFoundProblem: boolean | null;
}) {
  const state = agreement(telemetryFoundProblem, visual);
  const note = agreementNote(state);
  return (
    <section className="visual" aria-label="What the frame shows">
      <div className="vhead">
        <b>The frame</b>
        <span>
          {verdictLabel(visual.verdict)}
          {visual.confidence ? ` · ${visual.confidence} confidence` : ""}
        </span>
      </div>
      <p className="observation">{visual.observation}</p>
      {note ? <p className={state === "disagree" ? "relation clash" : "relation"}>{note}</p> : null}
      {visual.frame ? <p className="framepath">{visual.frame}</p> : null}
    </section>
  );
}

/** The line under the status word: how a shot stands against its date. */
function Delivery({ shot }: { shot: Shot }) {
  const landed = hasLanded(shot);
  const slack = describeSlack(shot.slack_seconds, landed);
  const eta = formatEta(shot.eta_epoch);
  const caveat = describeConfidence(shot.confidence);

  // Nothing honest to say is the ordinary state at the top of a render, and it renders as
  // nothing rather than a placeholder. A dash or a "0m" would read as a measurement, and
  // the whole point of the status is that a verdict has to be earned.
  if (!slack && !eta) return null;

  return (
    <>
      {slack ? <em>{slack}</em> : null}
      {eta ? (
        <em>
          {landed ? "finished" : "ETA"} {eta}
        </em>
      ) : null}
      {caveat ? <em className="caveat">{caveat}</em> : null}
    </>
  );
}

function ShotCard({ shot, base }: { shot: Shot; base: string }) {
  const { seq, shot: label, job } = parseId(shot.id);
  const diagnosis = normalizeDiagnosis(shot.diagnosis);
  const missed = shot.risk === "MISSED" || shot.risk === "CRITICAL";

  return (
    <article className={missed ? "card miss" : "card"}>
      <div className="slate">
        <span className="k">SCENE</span>
        <span className="v">{label}</span>
        <span className="k">ROLL</span>
        <span className="v">{job || seq || "-"}</span>
      </div>
      <div className="body">
        <div className="frames">
          {shot.frames_done}
          <span>/{shot.frames_total}</span>
        </div>
        <div
          className="track"
          role="img"
          aria-label={`${percent(shot.frames_done, shot.frames_total)} percent of frames rendered`}
        >
          <i style={{ width: `${percent(shot.frames_done, shot.frames_total)}%` }} />
        </div>
        <div className={`status s-${shot.risk}`}>
          <b>{shot.risk.replace("_", " ")}</b>
          <Delivery shot={shot} />
        </div>
        <DiagnoseButton apiBase={base} shotId={shot.id} hasDiagnosis={diagnosis !== null} />
      </div>
    </article>
  );
}

export default async function Board() {
  // Read once for the whole page. Calling Date.now() inside each card would let two rows
  // rendered a second apart disagree about what "3m ago" means.
  const nowEpoch = Math.floor(Date.now() / 1000);
  const { shots, error, telemetryReadable } = await fetchShots();
  const base = apiBase();
  const rows = shots.map((shot) => ({ shot, diagnosis: normalizeDiagnosis(shot.diagnosis) }));
  const diagnosed = rows.filter((row) => row.diagnosis !== null).length;
  const stale = stalenessNotice(rows.length > 0, telemetryReadable);

  return (
    <main className="wrap">
      <div className="mast">
        <h1>
          <Link href="/" style={{ textDecoration: "none" }}>
            {/* The mark is the mast's own motif: a clapper over a grid of frames, one of
                them magenta. Decorative here because the wordmark beside it already
                names the product. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/icon.svg" alt="" width={34} height={34} className="mark" />
            Dailies
          </Link>
        </h1>
        <div className="stripe" aria-hidden="true" />
        <div className="count">
          {shots.length} WATCHED{diagnosed > 0 ? ` · ${diagnosed} DIAGNOSED` : ""}
        </div>
      </div>

      {error ? (
        <p className="error">
          No shot data.
          <code>{error}</code>
        </p>
      ) : rows.length === 0 ? (
        <p className={telemetryReadable ? "empty" : "empty unreadable"}>
          {emptyMessage(telemetryReadable)}
        </p>
      ) : (
        <>
          {stale ? <p className="empty unreadable">{stale}</p> : null}
          {/* The producer's paragraph, above the instrument. A supervisor reads the grid;
              a producer wants one sentence about whether anything needs them. */}
          <p className="briefing">{briefing(shots)}</p>
          <div className="grid">
            {rows.map(({ shot }) => (
              <ShotCard key={shot.id} shot={shot} base={base} />
            ))}
          </div>
          {rows
            .filter((row) => row.diagnosis !== null)
            .map(({ shot, diagnosis }) => {
              const visual = normalizeVisual(shot.visual ?? null);
              return (
                <div key={shot.id}>
                  <Report
                    shotId={shot.id}
                    diagnosis={diagnosis as Diagnosis}
                    answeredAt={shot.answered_at}
                    stale={shot.answer_stale}
                    nowEpoch={nowEpoch}
                  />
                  {visual ? (
                    <VisualPanel
                      visual={visual}
                      telemetryFoundProblem={diagnosis?.problemFound ?? null}
                    />
                  ) : null}
                </div>
              );
            })}
        </>
      )}
    </main>
  );
}
